feat(receiver-mock): drop support for graphite and carbon 2.0
SumoLogic/sumologic-kubernetes-tools pull request #313
Opened 2022-08-23 10:45 UTC by aboguszewski-sumo

These metrics formats are not supported by our `sumologic` exporter in the otel collector.
Please confirm if it's safe to remove them (I tried checking it in collection repo, but with no success).

2022-08-23 10:50 UTC, sumo-drosiek commented
those are supported by fluentd, I would leave it as long as we claim support for fluentd

https://github.com/sumologic/fluentd-output-sumologic

> metric_data_format - The format of metrics you will be sending, either graphite or carbon2 or prometheus (Default is graphite )

2022-08-23 10:52 UTC, aboguszewski-sumo commented
Fine then. Let's just leave this for later.

2022-11-30 08:12 UTC, sumo-drosiek requested changes
to avoid merge possibility (can be dismissed if needed)

2022-12-01 08:10 UTC, aboguszewski-sumo commented
@sumo-drosiek what do you mean by that?

2024-06-04 13:21 UTC, sumo-drosiek approved these changes
Lets do it 💪

2024-06-10 10:25 UTC, sumo-drosiek requested changes
We shouldn't remove it as long as we support the format in any of our components:

- Helm chart v3
- [Collectd plugin](https://github.com/SumoLogic/sumologic-collectd-plugin/blob/aaa00c5ba5c04b67bc212025a0300af871f795e9/sumologic_collectd_metrics/metrics_config.py#L40)

2024-06-10 10:46 UTC, swiatekm-sumo commented
We should leave this be and close the PR, then.

2024-06-10 12:11 UTC, closed without merging

2024-06-10 12:11 UTC, aboguszewski-sumo commented
I agree, we did not manage to get rid of them in 2 years, so it's nothing urgent and potentially causes more problems than benefits.