log symlink checker
SumoLogic/sumologic-kubernetes-tools pull request #40
Opened 2020-08-24 23:05 UTC by samjsong

We want to add this bash script to the kubernetes tools so that we can recreate any log symlinks that kubernetes has deleted. This is based on a known open issue as referenced in the comment in-code

The idea would be to deploy this as a cronjob to run every few minutes. Please let me know if the below change looks reasonable :) 

I've verified that the script itself seems to work fine - I built it in a separate docker image and deployed on a test cluster.

But I'm new to kubernetes tools - how can I build and test this? Once I run `ci/build.sh` to build the docker image, what are the next steps for testing? Thanks team!

2020-08-25 07:34 UTC, sumo-drosiek commented
I believe we should run this as separate command, because in current shape we are going to make a lot of checks in addition to this one, especially `/usr/bin/k8s-api-test`

2020-08-25 09:29 UTC, sumo-drosiek commented
> But I'm new to developing for kubernetes tools - how can I build and test this? Once I run `ci/build.sh` to build the docker image, what are the next steps for testing? Thanks team!

I'm testing this in our k8s collection vagrant environment. You can push the docker to the vagrant repository with this commands:
```
docker tag sumologic/kubernetes-tools:local 192.168.78.66:32000/sumologic/kubernetes-tools:local
docker push 192.168.78.66:32000/sumologic/kubernetes-tools:local
```

**Note: You have to add 192.168.78.66:32000 as insecure docker registry in docker configuration**

and in the vagrant
```
kubectl run tools \
 -it --rm \
 --restart=Never \
 --image 127.0.0.1:32000/sumologic/kubernetes-tools:local \
 -- <command you want to test>
```

2020-08-25 23:21 UTC, samjsong commented
I've moved the symlink checker to a different command, but I realized that running this will only create a single pod - so we'd only be checking for the node that the pod ends up on. Is there a way to update how kubernetes tools will deploy the pod so that it can be run as a daemonset for this command?

2020-08-27 09:31 UTC, perk-sumo reviewed
This actually fixes the log symlinks, so I propose the change the function and script names into `fix-log-symlinks`.

2020-08-27 09:31 UTC, perk-sumo commented on src/commands/check-symlinks
> +function check_log_symlinks() {
```suggestion
function fix_log_symlinks() {
```

2020-08-27 09:31 UTC, perk-sumo commented on deploy/docker/Dockerfile
> +ADD ./src/commands/check-symlinks /usr/bin/check-symlinks
```suggestion
ADD ./src/commands/fix-log-symlinks /usr/bin/fix-log-symlinks
```

2020-08-27 09:31 UTC, perk-sumo commented on src/commands/check-symlinks
> +check_log_symlinks
```suggestion
fix_log_symlinks
```

2020-08-27 09:31 UTC, perk-sumo commented on src/commands/check-symlinks
> +#!/usr/bin/env bash
Please rename the file into `fix-log-symlinks`.

2020-08-27 11:08 UTC, perk-sumo requested changes
@samjsong I think we should also add a (disabled by default) option for the sleep loop like https://github.com/kubernetes/kubernetes/issues/50689#issuecomment-322480599

2020-08-27 16:20 UTC, sumo-drosiek commented on src/commands/check-symlinks
> +    LOG_PATH="$(echo ${CONTAINER} | jq -r .LogPath)"
```suggestion
    LOG_PATH="$(echo ${CONTAINER} | jq -r '.LogPath')"
```

2020-08-27 16:26 UTC, sumo-drosiek commented
except the @perk-sumo findings, LGTM

2020-08-27 16:26 UTC, sumo-drosiek approved these changes

2020-09-02 11:34 UTC, perk-sumo commented
@sumo-drosiek please review my last commit: db71ecfc47387b8a93fed7620e157b4feee3dd72

2020-09-02 13:23 UTC, sumo-drosiek commented
LGTM 🚀

2020-09-02 13:24 UTC, perk-sumo approved these changes
I've added some improvements and I like it now 😜 
@samjsong please review as well and merge if you are 👍

2020-09-03 06:17 UTC, samjsong commented
LGTM! Thanks a lot Perk 😛

2020-09-03 06:17 UTC, merged